---
# defaults file for ddns

# Which IP should be used for the record: external/internal
ddns_what_ip: "external"

# DNS A record to be updated, you can separate multiple records by comma
ddns_dns_record: "ip.example.tld"

# Cloudflare's Zone ID, you can find this on the landing/overview page of your domain.
ddns_zoneid: ""

# Cloudflare Zone API Token
ddns_cloudflare_zone_api_token: ""

# Use Cloudflare proxy on dns record true/false
ddns_proxied: "false"

# 120-7200 in seconds or 1 for Auto
ddns_ttl: 1

# Telegram Notifications yes/no (only sent if DNS is updated)
ddns_notify_me_telegram: "no"

# Telegram Chat ID
ddns_telegram_chat_id: "ChangeMe"

# Telegram Bot API Key
ddns_telegram_bot_API_Token: "ChangeMe"

